apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "papervault.fullname" . }}-web
  labels:
    {{- include "papervault.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      {{- include "papervault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "papervault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "papervault.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext.web | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext.web | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: nginx-run
              mountPath: /run
            - name: nginx-cache
              mountPath: /var/cache/nginx
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
      volumes:
        - name: nginx-run
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
