apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "papervault.fullname" . }}-worker
  labels:
    {{- include "papervault.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "papervault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "papervault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "papervault.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext.worker | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext.worker | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "papervault.configMapName" . }}
            - secretRef:
                name: {{ include "papervault.secretName" . }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
