{{- if or .Values.ingress.web.enabled .Values.ingress.api.enabled }}
{{- if .Values.ingress.web.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "papervault.fullname" . }}-web
  labels:
    {{- include "papervault.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.ingress.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.web.className }}
  ingressClassName: {{ .Values.ingress.web.className | quote }}
  {{- end }}
  {{- with .Values.ingress.web.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.web.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "papervault.fullname" . }}-web
                port:
                  name: http
---
{{- end }}
{{- if .Values.ingress.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "papervault.fullname" . }}-api
  labels:
    {{- include "papervault.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.api.className }}
  ingressClassName: {{ .Values.ingress.api.className | quote }}
  {{- end }}
  {{- with .Values.ingress.api.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.api.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "papervault.fullname" . }}-api
                port:
                  name: http
{{- end }}
{{- end }}
