apiVersion: v1
kind: ConfigMap
metadata:
  name: papervault-config
  namespace: papervault
data:
  PAPERVAULT_ENV: production
  PAPERVAULT_LOG_LEVEL: INFO
  PAPERVAULT_AUTH_ALLOW_DEV_HEADERS: "false"
  PAPERVAULT_LOCAL_AUTH_ENABLED: "true"
  PAPERVAULT_LOCAL_REGISTRATION_ENABLED: "false"
  PAPERVAULT_OCR_PROVIDER: tesseract
  PAPERVAULT_OCR_LANGUAGES: eng
  PAPERVAULT_OCR_TIMEOUT_SECONDS: "120"
  PAPERVAULT_OCR_PDF_DPI: "200"
  PAPERVAULT_OCR_MAX_PDF_PAGES: "50"
  PAPERVAULT_SEARCH_INDEX_ENABLED: "true"
  OPENSEARCH_DOCUMENTS_INDEX: papervault-documents-v1
  OPENSEARCH_TIMEOUT_SECONDS: "5"
